---
- name: Running show commands on Cisco IOS
  hosts: routers
  gather_facts: no
  connection: network_cli
  #  become: yes
  # become_method: enable

  # vars:
  #    ansible_user: jeevan
  #       ansible_ssh_pass: cisco
  #       ansible_become_pass: cisco
  #          ansible_network_os: ios

  tasks:
          - name: Run multiple commands on Cisco IOS nodes
            ios_command:
                    commands:
                            - show run
            register: output

          - debug: var=output.stdout_lines
...
