---
- name: Running show commands on Cisco IOS
  hosts: routers
  gather_facts: false
  connection: network_cli

  tasks:
          - name: Run multiple commands on Cisco IOS nodes
            ios_command:
                    commands:
                            - show version
                            - show ip interface brief
            register: output

          - debug: var=output.stdout_lines
...
